In [9]:
#script for analysis

import numpy as np
import pandas as pd
import cleaned_data as data
from sklearn import linear_model as lm


train = data.train


# now, make a make design matrix for models
# only features I believe matter are age, sex, class, and fare (maybe cabin location
# also matters?? check later)

survival = train.Survived
predictors = train[['Sex', 'Age', 'Fare', 'Pclass']]

y = survival.values
X = predictors.values



#analysis
mdl = lm.LogisticRegression()
mdl.fit(X,y)

#see how well this predicts the training data
prediction = mdl.predict(X)

summary = pd.DataFrame()
summary['true'] = y
summary['prediction'] = prediction

In [10]:
summary

     true  prediction
0       0           0
1       1           1
2       1           1
3       1           1
4       0           0
5       0           0
6       0           0
7       0           0
8       1           1
9       1           1
10      1           1
11      1           1
12      0           0
13      0           0
14      0           1
15      1           1
16      0           0
17      1           0
18      0           1
19      1           1
20      0           0
21      1           0
22      1           1
23      1           0
24      0           1
25      1           1
26      0           0
27      0           1
28      1           1
29      0           0
..    ...         ...
861     0           0
862     1           1
863     0           1
864     0           0
865     1           1
866     1           1
867     0           0
868     0           0
869     1           0
870     0           0
871     1           1
872     0           0
873     0           0
874     1           1
875     1           1
876     0           0
877     0           0
878     0           0
879     1           1
880     1           1
881     0           0
882     0           1
883     0           0
884     0           0
885     0           1
886     0           0
887     1           1
888     0           1
889     1           0
890     0           0

[891 rows x 2 columns]